/* oxlint-disable react/react-compiler -- Effects synchronize external storage and cancellable source requests; the React compiler is not enabled. */
/* oxlint-disable jsx-a11y/prefer-tag-over-role -- Status containers intentionally include multiple semantic child elements. */
'use client';
import { useEffect, useState } from 'react';
import type { LucideIcon } from 'lucide-react';
import { Activity, ArrowRight, ArrowUpRight, Bookmark, Database, GitCompareArrows, History, Info, Pill, Search, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select';
import type { Product } from '@/lib/types';
import { CompareView, ProductCard, ProductDetail, SearchResults, SourceDirectory } from './research-views';

const nav: [string,string,LucideIcon][] = [['explore','Medication explorer',Search],['compare','Compare medications',GitCompareArrows],['saved','Saved research',Bookmark],['sources','Sources & coverage',Database]];
const features: [LucideIcon,string,string,string][] = [[History,'Follow the label history','See what changed between published versions, from listed ingredients to safety wording.','01'],[GitCompareArrows,'Put the evidence side by side','Compare exact products, countries, and documented interaction passages.','02'],[Activity,'Explore reported experiences','Investigate suspected adverse reactions with their source and limitations in view.','03']];
export default function MedCheck() {
  const [query, setQuery] = useState(''); const [view, setView] = useState('explore');
  const [submitted,setSubmitted]=useState(''),[market,setMarket]=useState('US'),[selected,setSelected]=useState<Product|null>(null),[saved,setSaved]=useState<Product[]>([]),[comparison,setComparison]=useState<Product[]>([]),[message,setMessage]=useState(''),[ready,setReady]=useState(false);
  useEffect(()=>{try{const data=JSON.parse(localStorage.getItem('medcheck-saved')||'[]');if(Array.isArray(data))setSaved(data.filter(p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&Array.isArray(p.ingredients)).slice(0,100));}catch{setMessage('Saved research could not be read on this device.');}setReady(true);},[]);
  useEffect(()=>{if(ready)try{localStorage.setItem('medcheck-saved',JSON.stringify(saved));}catch{setMessage('This browser could not save research. You can still explore medications.');}},[saved,ready]);
  useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),6000);return()=>clearTimeout(timer);},[message]);
  function save(p:Product){setSaved(old=>old.some(s=>s.id===p.id)?old.filter(s=>s.id!==p.id):[p,...old].slice(0,100));}
  function compare(p:Product){if(comparison.some(c=>c.id===p.id)){setView('compare');return;}if(comparison.length>=2){setView('compare');setMessage('Remove one medication before adding another.');return;}setComparison(old=>[...old,p]);setMessage('Added to comparison.');if(comparison.length===1)setView('compare');}
  function open(p:Product){setSelected(p);setView('explore');window.scrollTo({top:0,behavior:'smooth'});}
  function search(q:string){setQuery(q);setSubmitted(q.trim());setSelected(null);setView('explore');}
  const title=view==='sources'?'Sources you can trace.':view==='saved'?'Keep your research close.':'Understand what’s changed.';
  const subtitle=view==='saved'?'Bookmarks are saved only in this browser. They are not a medical record.':'Explore medication history, listed ingredients, and the evidence behind reported reactions.';
  return <SidebarProvider style={{ '--sidebar-width': '232px' } as React.CSSProperties}>
    <Sidebar><SidebarHeader className="brand"><span className="brand-icon"><Pill size={23} /></span><span>medcheck<span className="brand-dot">.</span></span></SidebarHeader>
      <SidebarContent className="nav-body"><p className="eyebrow">WORKSPACE</p><SidebarMenu>{nav.map(([id,label,Icon])=><SidebarMenuItem key={id}><SidebarMenuButton isActive={view===id} onClick={()=>setView(id)} className="nav-item"><Icon size={18}/><span>{label}</span>{id==='compare'&&comparison.length>0&&<span className="nav-count">{comparison.length}</span>}{id==='saved'&&saved.length>0&&<span className="nav-count">{saved.length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent>
      <SidebarFooter><div className="sidebar-note"><ShieldCheck size={21}/><strong>Evidence, with context.</strong><p>Public sources. Clear provenance.<br/>Your research stays yours.</p></div><div className="sidebar-bottom"><span className="tiny-dot"/>Independent medication research</div></SidebarFooter></Sidebar>
    <SidebarInset><header className="topbar"><div><SidebarTrigger/><span className="muted">Workspace</span><span className="slash">/</span><span>{nav.find(n=>n[0]===view)?.[1]}</span></div><span className="privacy-note"><ShieldCheck size={15}/>No account needed</span></header>
    <main id="main" className="workspace">{message&&<div className="toast-message" role="status">{message}</div>}{view!=='compare'&&!(view==='explore'&&selected)&&<div className="page-heading"><div><p className="eyebrow teal">MEDICATION RESEARCH</p><h1>{title}</h1><p className="subtitle">{subtitle}</p></div><span className="research-badge"><Activity size={16}/>Research workspace</span></div>}
    {view==='sources'?<SourceDirectory/>:view==='compare'?<CompareView products={comparison} remove={id=>setComparison(old=>old.filter(p=>p.id!==id))} add={()=>{setSelected(null);setView('explore');}}/>:view==='saved'?<>{saved.length?<div className="results-grid">{saved.map(p=><ProductCard key={p.id} p={p} open={()=>open(p)} compare={()=>compare(p)} saved onSave={()=>save(p)} inCompare={comparison.some(c=>c.id===p.id)}/>)}</div>:<div className="empty-state panel"><Bookmark size={30}/><h2>Your research starts with a medication</h2><p>Save a product to find its history and evidence here later, on this device.</p><Button onClick={()=>setView('explore')}>Explore medications <ArrowRight size={16}/></Button></div>}</>:selected?<ProductDetail key={selected.id} p={selected} back={()=>setSelected(null)} onCompare={()=>compare(selected)} onSave={()=>save(selected)} saved={saved.some(p=>p.id===selected.id)}/>:<>
      <section className="search-panel"><div className="search-intro"><span className="search-icon"><Search size={21}/></span><div><h2>Start with a medication</h2><p>A brand name, ingredient, NDC, or Canadian DIN.</p></div></div><form className="search-form" onSubmit={e=>{e.preventDefault();search(query);}}><Input aria-label="Search medications" placeholder="Search a medication, e.g. sertraline" value={query} onChange={e=>setQuery(e.target.value)}/><NativeSelect aria-label="Medication market" value={market} onChange={e=>setMarket(e.target.value)}><NativeSelectOption value="US">United States</NativeSelectOption><NativeSelectOption value="CA">Canada</NativeSelectOption></NativeSelect><Button disabled={query.trim().length<3} type="submit" size="lg">Search medications <ArrowRight size={17}/></Button></form><div className="suggestions"><span>Try a search</span>{['Sertraline','Atorvastatin','Metformin'].map(q=><button key={q} onClick={()=>search(q)}>{q}<ArrowUpRight size={13}/></button>)}</div></section>
      {submitted?<SearchResults query={submitted} market={market} onOpen={open} onCompare={compare} saved={saved} onSave={save} comparison={comparison}/>:<div className="research-layout"><section><div className="section-heading"><h2>A closer look at your medication</h2><span className="muted">From the source</span></div><div className="feature-rows">{features.map(([Icon,title,desc,n])=><article key={n} className="feature-row"><span className="feature-number">{n}</span><div className="feature-icon"><Icon size={23}/></div><div><h3>{title}</h3><p>{desc}</p></div><ArrowUpRight className="row-arrow" size={19}/></article>)}</div><div className="evidence-note"><Info size={19}/><p>A label update isn’t always a formulation change. A reported reaction isn’t proof of causation. MedCheck keeps those distinctions visible.</p></div></section><aside className="panel coverage-card"><div className="section-heading"><h2>Connected to the source</h2><Database size={19}/></div><p>Research across national data sources, with each origin clearly identified.</p><div className="country-row"><span className="country-code">US</span><div><strong>United States</strong><small>DailyMed · RxNorm · openFDA</small></div></div><div className="country-row"><span className="country-code">CA</span><div><strong>Canada</strong><small>Health Canada · Canada Vigilance</small></div></div><div className="coverage-footer"><span className="tag">WHO & EMA references</span><button onClick={()=>setView('sources')}>Explore all sources <ArrowRight size={15}/></button></div></aside></div>}
    </>}<footer className="workspace-footer"><span>Medication research, with the evidence in view.</span><span>For information · Discuss medication decisions with your care team.</span></footer></main></SidebarInset>
  </SidebarProvider>;
}
