import type { SourceStatus } from './types';
export const sources: SourceStatus[] = [
  { id: 'dailymed', name: 'DailyMed', region: 'United States', description: 'Versioned product labels, listed ingredients, and prescribing information.', url: 'https://dailymed.nlm.nih.gov/dailymed/', access: 'integrated', status: 'Available on request' },
  { id: 'rxnorm', name: 'RxNorm', region: 'United States', description: 'Medication names, ingredients, synonyms, and identifier history.', url: 'https://lhncbc.nlm.nih.gov/RxNav/', access: 'integrated', status: 'Available on request' },
  { id: 'openfda', name: 'openFDA', region: 'US reporting authority', description: 'Current labels, historical recalls, and adverse-event reports. Report origin can be outside the US.', url: 'https://open.fda.gov/apis/drug/', access: 'integrated', status: 'Available on request' },
  { id: 'dpd', name: 'Drug Product Database', region: 'Canada', description: 'Canadian products, active ingredients, strengths, routes, and marketing status.', url: 'https://health-products.canada.ca/dpd-bdpp/index-eng.jsp', access: 'integrated', status: 'Available on request', termsUrl: 'https://open.canada.ca/en/open-government-licence-canada' },
  { id: 'cv', name: 'Canada Vigilance', region: 'Canada', description: 'Published reports of suspected adverse reactions occurring in Canada. Updated through validated dataset imports.', url: 'https://www.canada.ca/en/health-canada/services/drugs-health-products/medeffect-canada/adverse-reaction-database.html', access: 'integrated', status: 'Checking import status', termsUrl: 'https://www.canada.ca/en/health-canada/services/drugs-health-products/medeffect-canada/adverse-reaction-database/medeffect-canada-caveat-privacy-statement-interpretation-data-extract-vigilance-adverse-reaction-online-database.html' },
  { id: 'who', name: 'WHO · VigiAccess', region: 'Global', description: 'Explore WHO adverse-reaction aggregates on the official portal. Direct API access requires a separate agreement.', url: 'https://www.vigiaccess.org/', access: 'external', status: 'External reference' },
  { id: 'ema', name: 'EMA · EudraVigilance', region: 'EEA and non-EEA reports', description: 'European public adverse-reaction reports. Portal totals may include events outside Europe.', url: 'https://www.adrreports.eu/en/search_subst.html', access: 'external', status: 'External reference' },
];
export const reportCaveat = 'These are reports of suspected events, not proof that a medication caused a reaction. Counts cannot tell you how likely a reaction is or which medication is safer. A report can mention several medicines and reactions.';
export const canadaCaveat = 'Canada Vigilance contains suspected adverse reactions. Reports can be incomplete or duplicated; the latest follow-up is retained. Counts do not establish causation, incidence, or comparative safety. Contains information licensed under the Open Government Licence – Canada.';
